=head1 HappyJar

=head2 About

This is a dumb Mojolicious app I wrote a long time ago to record happy
thoughts for the year, and then review them at the end of the year. It runs on
Heroku.

If I were writing it from scratch, I'd do a lot of things differently.
But...the code still runs, and is almost completely maintenance-free, so I'm
happy just to update it once a year and let it keep running.


=head2 License/Contact

Licensed under the same terms as Perl itself: see
L<http://www.perlfoundation.org/artistic_license_2_0> for details. Contact me
at L<michael@mcclimon.org>.


